version: '3'

services:
  #Image for php
  web:
    build:
      context: images/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    networks:
      - nginx-php-postgres-network

  #Image for proxy server
  proxy:
    build:
      context: images/proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-80}:80
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./www/public:/var/www/public
      - ./images/proxy:/etc/nginx/conf.d/
    networks:
      - nginx-php-postgres-network

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    networks:
      - nginx-php-postgres-network

  db:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-password}
      POSTGRES_USER: ${USER_LOGIN:-login}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres
    networks:
      - nginx-php-postgres-network

volumes:
  dbdata:
    driver: local

networks:
  nginx-php-postgres-network:
    driver: bridge